[package]
name = "confus"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.0"
env_logger = "0.10.0"
log = "0.4.17"
prost = "0.11.9"
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tonic = "0.9.2"

[build-dependencies]
tonic-build = "0.9.2"
