apiVersion: apps/v1
kind: Deployment
metadata:
  name: keys
  namespace: vpnaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keys
  template:
    metadata:
      labels:
        app: keys
    spec:
      containers:
      - name: keys
        image: mekstack/keys:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: RUST_LOG
          value: info
        - name: VPNAAS_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keys
              key: redis-pass
        - name: VPNAAS_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mekstack
              key: jwt-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: keys
  namespace: vpnaas
spec:
  selector:
    app: keys
  ports:
  - protocol: TCP
    port: 80
