apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: vpnaas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: vpnaas
data:
  redis.conf: |-
    aclfile /secret/users.acl
    appendonly yes
    appendfsync everysec
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: vpnaas
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        args: ["redis-server", "/config/redis.conf"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        - name: secret
          mountPath: /secret
      volumes:
      - name: config
        configMap:
          name: redis-config
      - name: data
        persistentVolumeClaim:
          claimName: redis-data
      - name: secret
        secret:
          secretName: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vpnaas
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
