apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg
  namespace: vpnaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg
  template:
    metadata:
      labels:
        app: wg
    spec:
      containers:
      - name: wg
        image: mekstack/wg:latest
        imagePullPolicy: Never
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
        ports:
        - containerPort: 80
        env:
        - name: RUST_LOG
          value: info
        - name: VPNAAS_WGDEVICE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: wg
              key: privkey
---
apiVersion: v1
kind: Service
metadata:
  name: wg
  namespace: vpnaas
spec:
  selector:
    app: wg
  ports:
  - protocol: TCP
    port: 80
