apiVersion: v1
kind: Service
metadata:
  name: wg-wireguard-lb
  labels:
    {{- include "vpnaas.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: vpnaas-helm
    app.kubernetes.io/name: wg
  ports:
  - port: 51820
    targetPort: 51820
    protocol: UDP
  loadBalancerIP: 172.18.218.100
