{{- range $name, $microserviceValues := .Values.microservices }}
---
{{- $microserviceValues := merge $.Values.microservicesCommon $microserviceValues }}
{{- $finalValues := merge (dict "name" $name) $microserviceValues }}
{{- include "common.microservice" (dict "Values" $finalValues "Chart" $.Chart "Release" $.Release) }}
{{- end }}
