{{- range tuple "keys" "wg" "confus" "web" }}
{{ include "saas-lib.microservice" (
        include "vpnaas.microservice-config"
            (dict
                "name" .
                "context" $
            )
        | fromYaml
    )
}}
---
{{- end -}}
