{{- range tuple "keys" "wg" "confus" "web" }}
{{- $_ := mergeOverwrite $ (dict "name" .) -}}
{{ include "saas-lib.microservice" (
        include "saas-lib.microservice-config"
            (dict
                "context" $
                "name" .
                "labels" (include "vpnaas.labels" $ | fromYaml)
                "selectorLabels" (include "vpnaas.selectorLabels" $ | fromYaml)
            )
        | fromYaml
    )
}}
---
{{- end -}}
