nameOverride: ""

microservices:
  _default:
    name: ""
    repository: mekstack/vpnaas
    pullPolicy: Never
    tag: latest
    securityContext: {}
    env:
      - name: RUST_LOG
        value: info
    labels: {}
    selectorLabels: {}

  keys:
    env:
    - name: VPNAAS_REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keys
          key: redis-pass
    - name: VPNAAS_JWT_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: mekstack
          key: jwt-secret-key
  wg:
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_MODULE
    env:
    - name: VPNAAS_WGDEVICE_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: wg
          key: privkey
  confus:
    env:
    - name: VPNAAS_CONFIG_ENDPOINT
      value: wg.mekstack.ru
    - name: VPNAAS_CONFIG_PUBKEY
      value: mZjqLnMXtQUpPLu1ntq2PgrG75HDarhvywvmT7M9gQo
    - name: VPNAAS_CONFIG_ALLOWED_IPS
      value: 0.0.0.0/0
    - name: VPNAAS_CONFIG_DNS
      value: 8.8.8.8
  web: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
